### ISSUE TITLE
Filtering parameters similar to rails' filter_parameters

### ISSUE THREAD

**Issue by stephenbinns** [gshutler/hatchet#13]
It would be useful to filter out sensitive details from logs at a global level - similar to how rails does this could also be inherited from the rails configuration

**Comment by gshutler** [comment]
That's an application-level concern, not a logging one. Rails [builds it into the framework](https://github.com/rails/rails/blob/970fe27b02fa7df9e01276861adebc131083958c/actionpack/lib/action_dispatch/http/filter_parameters.rb) and utilises those methods rather than their raw equivalent where appropriate.
